# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('homepage', models.URLField()),
                ('career_goal', models.TextField()),
                ('nationality', models.CharField(max_length=120)),
                ('interests', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=120)),
                ('course_text', models.CharField(max_length=120)),
                ('course_date_completed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('employer', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('job_type', models.CharField(choices=[('parttime', 'Part Time'), ('fulltime', 'Full Time'), ('contract', 'Contract'), ('temporary', 'Temp'), ('voluntary', 'Volunteer')], default='fulltime', max_length=120)),
                ('current_job', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('skill_type', models.CharField(choices=[('business', 'Business'), ('technical', 'Technical')], max_length=120)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_skills',
            field=models.ManyToManyField(to='myCV.Skill'),
        ),
        migrations.AddField(
            model_name='achievements',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myCV.Job'),
        ),
    ]
