# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.AlterField(
            model_name='education',
            name='course_date_completed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(),
        ),
    ]
